projects: []

clusters:
  - server:      https://kubernetes.default.svc
    name:        aks-lab
    projectId:   default
    region:      westeurope
    argoProject: default
    stage:       staging

    genericApps:

      - chart: betisapp17
        namespace: lab
        valueFiles:
          - values.yaml
        syncPolicy:
          syncOptions:
          - CreateNamespace=true        

      - chart: kuard
        namespace: lab
        valueFiles:
          - values.yaml
        syncPolicy:
          syncOptions:
          - CreateNamespace=true        

      # - chart: podinfo
      #   namespace: lab
      #   valueFiles:
      #     - values.yaml
      #   syncPolicy:
      #     syncOptions:
      #     - CreateNamespace=true        

