projects:
  - lab

clusters:
  - server:      https://kubernetes.default.svc
    name:        aks-lab
    projectId:   lab
    region:      westeurope
    argoProject: lab
    stage:       staging

    genericApps:

      - chart: betisapp
        namespace: lab
        valueFiles:
          - values.yaml

      - chart: kuard
        namespace: lab
        valueFiles:
          - values.yaml

      # - chart: podinfo
      #   namespace: lab
      #   valueFiles:
      #     - values.yaml

