projects:
  - lab

clusters:
  - server:      https://aks-41psjrck.hcp.westeurope.azmk8s.io
    name:        aks-41psjrck
    projectId:   lab
    region:      westeurope
    argoProject: lab
    stage:       staging

    genericApps:

      - chart: betisapp
        namespace: lab
        valueFiles:
          - values.yaml

      - chart: kuard
        namespace: lab
        valueFiles:
          - values.yaml

      # - chart: podinfo
      #   namespace: lab
      #   valueFiles:
      #     - values.yaml

